name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome - please be sure to let me know you stopped by [eritzman@gmail.com](mailto:eritzman@gmail.com)"
        pr-message: "Thank you for your contribution - please bare with me as I review your input."
